### ISSUE TITLE
Can't find sys/times.h during vscode building in windows 7

### ISSUE THREAD

**Issue by zzzh** [littlevgl/lv_platformio#10]
Below is the building output:

> Executing task: E:\Cadence\SPB_Data\.platformio\penv\Scripts\platformio.exe run <

Processing native (platform: native)
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
PACKAGES:
LDF: Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 2 compatible libraries
Scanning dependencies...
Dependency Graph
|-- <lvgl> 6.0.2
|-- <lv_drivers> 6.0.2
|   |-- <lvgl> 6.0.2
Compiling .pio\build\native\drivers\sdl2\driver.o
Compiling .pio\build\native\src\demo.o
Compiling .pio\build\native\src\img_bubble_pattern.o
Compiling .pio\build\native\src\main.o
Compiling .pio\build\native\src\syscalls.o
Compiling .pio\build\native\lib34d\lvgl_ID6598\lv_core\lv_disp.o
src\syscalls.c:56:10: fatal error: sys/times.h: No such file or directory
 #include <sys/times.h>
          ^~~~~~~~~~~~~
compilation terminated.
*** [.pio\build\native\src\syscalls.o] Error 1

**Comment by puzrin** [comment]
> which was claimed to be supported

Where it was done? Send PR to remove and avoid confusion.

**Comment by zzzh** [comment]
BTW: for mingw64 in windows, I'm using x86_64-8.1.0-release-posix-seh-rt_v6-rev0

**Comment by zzzh** [comment]
> 
> 
> > which was claimed to be supported
> 
> Where it was done? Send PR to remove and avoid confusion.

I think here: https://docs.littlevgl.com/en/html/get-started/pc-simulator.html

**Comment by puzrin** [comment]
I guess, doc predicts the future :). It's maintained by someone else. Ask on forum or in lvgl repo to clarify.

Also, i did not understood, are all targets broken or native only? Is stm32 target buildable?

**Comment by embeddedt** [comment]
@zzzh There is a difference between the PC simulator and the PlatformIO project. The documentation you are working with is not for PlatformIO.

If you are just looking to get a PC simulator on Windows try the [CodeBlocks](https://github.com/littlevgl/pc_simulator_win_codeblocks) or [Visual Studio](https://github.com/littlevgl/pc_simulator_sdl_visual_studio) projects. They should support Windows out of the box.

**Comment by zzzh** [comment]
Got it.
Took a try, stm32 works, only native have issue

**Comment by zzzh** [comment]
@embeddedt  Got it, thank you, I'll not use PlatformIO in windows.

**Comment by puzrin** [comment]
Since you are not first, who report such issue, probably README should be improved to avoid confusion.

Also, i'm sure SDL2 can be fixed for PIO + Win. But that requires volunteer, who is interested to spend time for that.

**Comment by puzrin** [comment]
https://github.com/littlevgl/lv_platformio/commit/c48729d0c6e2dbf4ae18315b4c4925abea5c5c49 added Windows note.
