### ISSUE TITLE
Repo description update

### ISSUE THREAD

**Issue by puzrin** [littlevgl/lv_platformio#5]
@kisvegabor seems need to remove BETA from repo's description & refresh text.

I'd suggest `Demo of use LittlevGL with PlatformIO`, or anything else of this kind.

**Comment by kisvegabor** [comment]
I've updated it to `PlatformIO project for LittlevGL`.
What do you think?

**Comment by puzrin** [comment]
May be `PlatformIO project example for LittlevGL`?

**Comment by kisvegabor** [comment]
It's fine too. 
Updated.
