### ISSUE TITLE
<SDL2/SDL.h> and other header files missing

### ISSUE THREAD

**Issue by Chronic788** [littlevgl/lv_platformio#7]
When I cloned the source code and followed the instructions to build using VSCode (found here: https://github.com/littlevgl/lv_platformio) I found that these header files are missing:

- <SDL2/SDL.h>
- indev/mouse.h
- indev/mousewheel.h
- indev/keyboard.h

**Comment by embeddedt** [comment]
Are you on Windows or Linux?

**Comment by Chronic788** [comment]
I am on Windows 64 bit. I've followed the instructions to install SDL2 from this page: https://docs.littlevgl.com/en/html/get-started/pc-simulator.html#install-sdl-2

After looking at things further, it seems my installation of MinGW is a little different than what the above link. I went to this page: http://mingw-w64.org/doku.php/download
and downloaded the MingW-W64-builds selection from sourceforge. It installed MinGW to C:\Program Files (x86) which is different than the documentation instructions say: they say it should be:  C:/MinGW/…/x86_64-w64-mingw32. Then I followed the instructions to copy the files from the download of the development files found here: https://www.libsdl.org/download-2.0.php . I am not sure that my MinGQ install is the problem, though. Would the copying of the SDL2 files be different for VSCode than Eclipse?

**Comment by puzrin** [comment]
I use linux, no ideas how to install sdl2 for win.

About `indev` - i had a very strange bug with different paths behaviour in windows/linux https://github.com/speedcontrols/ac_sc_grinder/pull/2, but not sure if it applies to this case. It really worth fix sdl2 path first.

**Comment by embeddedt** [comment]
@Chronic788 On Windows it's usually easiest to use the Visual Studio or CodeBlocks projects instead. They don't depend on an external library like SDL and thus are easier to set up.

**Comment by Chronic788** [comment]
I've resolved my problem by switching to Linux
