### ISSUE TITLE
Space in native build target

### ISSUE THREAD

**Issue by frankalicious** [littlevgl/lv_platformio#9]
Hi there.

Shouldn't it be `[env:native]` instead of `[env:nativ e]` in [platformio.ini](https://github.com/littlevgl/lv_platformio/blob/177aae6b0d39548e6263ced69c8a1df108feced0/platformio.ini#L14) (?  
If a space is used the executable is in ./.pio/build/nativ\ e/program and not in ./.pio/build/native/program.

**Comment by kisvegabor** [comment]
Hi,

Thanks. I've just fixed it and also made "native" as default environment.
